site_name: Citrix Workspace app 1808 for Linux OEM Reference Guide 
site_description: OEM Reference guide for Citrix Workspace app 1808 for Linux 
theme_dir: citrix-sdk

markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- Home: index.md
- Resources to Aid Customization: resources-to-aid-customization.md
- Tools: tools.md
- Citrix Workspace app for Linux Components: components.md
- Customize Citrix Workspace app for Linux: customize.md
- Experimental Features: experimental-features.md
- Reference Information: reference-information.md
